src/blog/urls.py
from django.urls import path 
from blog.views import(
	create_blog_view,
	detail_blog_view,
	edit_blog_view,
	)

app_name='blog'

urlpatterns=[  
	path('create', create_blog_view, name="create"),
	path('<slug>/', detail_blog_view, name="detail"),
	path('<slug>/edit', edit_blog_view, name="edit"),
]

src/mysite/urls.py
from django.contrib import admin

from django.urls import path, include
from django.conf.urls.static import static
from personal.views import home_screen_view
from django.contrib.auth import views as auth_views 
from django.conf import settings
from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
    must_authenticate_view,
)
 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', 'blog')),
    path('', home_screen_view, name="home"),
    path('register/', registration_view, name="register"),
    path('logout/', logout_view, name="logout"),
    path('login/', login_view, name="login"),
    path('account/', account_view, name="account"),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),

     # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/blog/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify 
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.conf import settings




# Create your models here.


def upload_location(instance, filename, **kwargs):
	file_path	=	'blog/{author_id}/{title}-{filename}'.format(
			author_id=str(instance.author.id), title=str(instance.title), filename=filename
		)
	return file_path

class BlogPost(models.Model):
	title		= models.CharField(max_length=50,null=False, blank =False)
	body	= models.TextField(max_length=500000,null=False, blank =False)
	image	= models.ImageField(upload_to=upload_location,null=False, blank =False)
	date_published	= models.DateTimeField(auto_now_add=True, verbose_name="date published")
	date_updated	= models.DateTimeField(auto_now=True, verbose_name="date updated")
	author	= models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
	slug	= models.SlugField(blank=True, unique=True)#like an URL

	def __str__(self):
		return self.title


@receiver(post_delete, sender=BlogPost)
def submission_delete(sender, instance, **kwargs):
	instance.image.delete(False)


def pre_save_blog_post_receiver(sender, instance, *args, **kwargs):
	if not instance.slug: 
		instance.slug=slugify(instance.author.username + "-" + instance.title)

pre_save.connect(pre_save_blog_post_receiver, sender=BlogPost)

src/blog/forms.py
from django import forms

from blog.models import BlogPost

class CreateBlogPostForm(forms.ModelForm):

	class Meta: 
		model = BlogPost
		fields = ['title', 'body', 'image']



class UpdateBlogPostForm(forms.ModelForm):

	class Meta: 
		model=BlogPost
		fields=['title', 'body', 'image']

	def save(self, commit=True):
		blog_post = self.instance
		blog_post.title=self.cleaned_data['title']
		blog_post.body=self.cleaned_data['body']

		if self.cleaned_data['image']:
			blog_post.image = self.cleaned_data['image']

		if commit:
			blog_post.save()

		return blog_post

src/blog/views.py
from django.shortcuts import render,redirect,get_object_or_404
from blog.models import BlogPost
from blog.forms import CreateBlogPostForm,UpdateBlogPostForm
from account.models import Account
from django.db.models import Q
from django.http import HttpResponse

# Create your views here.


def create_blog_view(request):
	context = {}
	user = request.user 
	if not user.is_authenticated: 
		return redirect('must_authenticate')

	form = CreateBlogPostForm(request.POST or None, request.FILES or None)
	if form.is_valid(): 
		obj	= form.save(commit=False)
		author = Account.objects.filter(email=user.email).first()
		obj.author=author
		obj.save()
		form=CreateBlogPostForm()

	context['form']=form

	return render(request, "blog/create_blog.html", context)

def detail_blog_view(request,slug):
	context={}
	blog_post=get_object_or_404(BlogPost, slug=slug)
	context['blog_post']=blog_post
	return render(request,'blog/detail_blog.html', context)


def edit_blog_view(request,slug):
	context={}
	user=request.user
	if not user.is_authenticated:
		return redirect('must_authenticate')

	blog_post = get_object_or_404(BlogPost, slug=slug)

	if blog_post.author !=user:
		return HttpResponse("You aint the one wrote this")

	if request.POST: 
		form = UpdateBlogPostForm(request.POST or None, request.FILES or None, instance=blog_post)
		if form.is_valid():
			obj = form.save(commit=False)
			obj.save()
			context['success_message'] = "Updated"
			blog_post = obj
	form = UpdateBlogPostForm(
			initial= {
				"title": blog_post.title,
				"body": blog_post.body,
				"image": blog_post.image,
			}
		)
	context['form']=form
	return render(request, 'blog/edit_blog.html', context)


def get_blog_queryset(query=None):
	queryset=[]
	queries=query.split(" ")
	for q in queries:
		posts = BlogPost.objects.filter(
				Q(title__icontains=q) |
				Q(body__icontains=q)
			).distinct()

		for post in posts: 
			queryset.append(post)
	return list(set(queryset))

src/blog/templates/blog/snippets/blog_post_pagination.html
<!-- FILTERED Pagination -->
<div class="d-flex flex-column m-auto pagination mt-5">
<nav aria-label="Page navigation">
<ul class="pagination pg-grey justify-content-center">
	{% if blog_posts.has_previous %}
        <li class="page-item">
		  <a class="page-link" style="background-color:#E5C09D; border-color: #E5C09D; color:black;" href="?{% if query %}q={{query}}&{% endif %}page={{ blog_posts.previous_page_number }}">&laquo; Previous</a>
		</li>
    {% endif %}

	{% for i in blog_posts.paginator.page_range %}
		{% if blog_posts.number == i %}
			<li class="page-item active"><a class="page-link" style="background-color:#E5C09D; border-color: #E5C09D; color:black;">{{ i }}</a></li>
		{% else %}
			<li class="page-item" ><a class="page-link" style="background-color:#E5C09D; border-color: #E5C09D; color:black;" href="?{% if query %}q={{query}}&{% endif %}page={{ i }}">{{ i }}</a></li>
		{% endif %}
	{% endfor %}
    
    {% if blog_posts.has_next %}
    	<li class="page-item">
		  <a class="page-link" style="color:black;"  href="?{% if query %}q={{query}}&{% endif %}page={{ blog_posts.next_page_number }}">Next</a>
		</li>
		<li class="page-item">
		  <a class="page-link" style="color:black;"  href="?{% if query %}q={{query}}&{% endif %}page={{ blog_posts.paginator.num_pages }}">Last &raquo;</a>
		</li>
    {% endif %}
</ul>
</nav>
</div>
<!-- end pagination-->

src/blog/templates/blog/snippets/blog_post_snippet.html
<style type="text/css">
	.card{
		max-width: 700px;
		width: 100%;
	}
	.card-body{
		padding: 20px;

	}
</style>

<div class="container">
	<div class="row">
		{% if blog_post %}
		<!-- Blog Post -->
		<div class="card m-auto">
			<a href="{% url 'blog:detail' post.slug %}">
				<img class="card-img-top" src="{{blog_post.image.url}}">
			</a>
			
			<div class="card-body mt-2 mb-2">
				<a href="{% url 'blog:detail' post.slug %}">
					<h2 class="card-title">{{blog_post.title}}</h2>
				</a>
				<p class="card-text">{{blog_post.body|safe|truncatechars:250}}</p>
				{% if blog_post.author == request.user %}
					<a href="{% url 'blog:edit' blog_post.slug %}" class="btn btn-primary" style="background-color:#E5C09D; border-color: #E5C09D;color:white">Update</a>
				{% endif %}
				
				
			</div>
			<div class="card-footer text-muted">
			  Updated on {{blog_post.date_updated}} by {{blog_post.author}}
			</div>
		</div>

	</div>
</div>

{% else %}

<div class="container">
	<div class="card m-auto">
		<div class="card-body mt-2 mb-2">
			<h2 class="class-title">
				No results
			</h2>
			<p class="card-text"> No matching results buddy! "{{query}}".</p>
		</div>
	</div>
</div>
{% endif %}