src/blog/urls.py
from django.urls import path 
from blog.views import(
	create_blog_view,
	detail_blog_view,
	edit_blog_view,
	)

app_name='blog'

urlpatterns=[  
	path('create', create_blog_view, name="create"),
	path('<slug>/', detail_blog_view, name="detail"),
	path('<slug>/edit', edit_blog_view, name="edit"),
]

src/mysite/urls.py
from django.contrib import admin

from django.urls import path, include
from django.conf.urls.static import static
from personal.views import home_screen_view
from django.contrib.auth import views as auth_views 
from django.conf import settings
from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
    must_authenticate_view,
)
 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', 'blog')),
    path('', home_screen_view, name="home"),
    path('register/', registration_view, name="register"),
    path('logout/', logout_view, name="logout"),
    path('login/', login_view, name="login"),
    path('account/', account_view, name="account"),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),

     # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/personal/models.py
from django.db import models

# # Create your models here.
# PRIORITY = [
# 	("L", "Low"),
# 	("M", "Medium"),
# 	("H", "High")

# ]

# class Question(models.Model):
# 	title					= models.CharField(max_length=60)
# 	question	 			= models.TextField(max_length=600)
# 	priority				= models.CharField(max_length=1,choices=PRIORITY)

# 	def _str_(self):
# 		return self.title

# 	class Meta: 
# 		verbose_name = "The Question"
# 		verbose_name_plural = "People Questions"

src/personal/views.py
from django.shortcuts import render
from operator import attrgetter
# from personal.models import Question
from account.models import Account
from blog.models import BlogPost
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from blog.views import get_blog_queryset

# Create your views here.


BLOG_POSTS_PER_PAGE=10
def home_screen_view(request):

	context = {}


	query = ""
	if request.GET: 
		query = request.GET.get('q', '')
		context['query'] = str(query)
	blog_posts= sorted(get_blog_queryset(query), key=attrgetter('date_updated'), reverse = True)
	

	# Pagination 
	page= request.GET.get('page', 1)
	blog_posts_paginator = Paginator(blog_posts, BLOG_POSTS_PER_PAGE)

	try: 
		blog_posts=blog_posts_paginator.page(page)
	except PageNotAnInteger:
		blog_posts=blog_posts_paginator.page(BLOG_POSTS_PER_PAGE)
	except EmptyPage:
		blog_posts=blog_posts_paginator.page(blog_posts_paginator.num_pages)

	context['blog_posts']=blog_posts

	return render(request, 'personal/home.html', context)

src/personal/templates/personal/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style type="text/css">

	@media (max-width: 768px) { 
		.right-column{
			margin-left: 0px;
		}
	}

	@media (min-width: 768px) { 
		.right-column{
			margin-left: 20px;
		}
	}

	.blog-post-container{
		margin-bottom: 20px;
		width: 100%;
	}
	.create-post-bar{
		background-color: #fff;
		margin-bottom:20px;
	}

	.left-column{
		padding:0px;
	}

	.right-column{
		padding:0px;
	}
	.lead{
		font-size: 17px;
	}
	.jumbotron{
    background: url(static/tunnel.jpg) no-repeat center center; 
    -webkit-background-size: 100% 100%;
    -moz-background-size: 100% 100%;
    -o-background-size: 100% 100%;
    background-size: 100% 100%;
    height: 600px;
    opacity: 0.9;
 
}
</style>

{% block head %}
<!-- banner -->
<div class="jumbotron jumbotron-fluid">
	
    <div class="text-white text-center pb-2 py-5 px-4">
        <div>
            <h1 class="display-5" style="font-family: Poppins; font-size: 150px;color: white">Stephen Blog</h1>
            <h4>"We must not allow other people's limited perceptions to define us."</h4>
            
        </div>
    </div>
</div>
{% endblock %}
<!-- main content -->
<div class="container">
	<div class="row">

		<!-- blog feed -->
		<div class="left-column col-lg-7 offset-lg-1">

			<!-- Top 'create post' bar -->
			<div class="d-lg-none mb-3">
				<div class="card m-auto d-flex flex-column p-3">
					<img class="img-fluid d-block m-auto pb-2" src="{% static 'a.png' %}" width="72" height="72">
					<p class="lead">Bonjour, this is my personal space of creating datascience-related contents along with some technical python gaming implementation. My feed is expected to be flooded with Stats and Prob knowledge and more real-world projects will be introduced as a way to my phD.</p>
					<p class="m-auto"><a class="btn btn-primary" style="background-color:#E5C09D;" href="{% url 'blog:create' %}">Create post</a></p>
				</div>
			</div>
			<!-- end Top 'create post' bar -->

			<!-- Blog posts-->
			{% if blog_posts %}
				{% for post in blog_posts %}
					<div class="blog-post-container">
						{% include 'blog/snippets/blog_post_snippet.html' with blog_post=post %}
					</div>
				{% endfor %}
			{% else %}
				<div class="blog-post-container">
					{% include 'blog/snippets/blog_post_snippet.html' with query=query %}
				</div>
			{% endif %}
			<!-- End Blog posts-->
			{% include 'blog/snippets/blog_post_pagination.html' with blog_posts=blog_posts %}
		</div>
		<!-- end blog feed -->

		<!-- Pagination -->



		<!-- Right 'create post' column  -->
		<div class="right-column col-lg-3 d-lg-flex d-none flex-column">

			<div class="card create-post-bar d-flex flex-column p-3">
				<img class="img-fluid d-block m-auto pb-2" src="{% static 'a.png' %}" width="72" height="72">
				<p class="lead" style="font-family: Poppins; align-content: center;">Bonjour, this is my personal space of creating datascience-related contents along with some technical python gaming implementations. My feed is expected to be bombarded with Stats and Prob ideas or unexpected real-world data projects</p>
				<p class="m-auto"><a class="btn btn-primary" style="background-color:#E5C09D; border-color: #E5C09D" href="{% url 'blog:create' %}">Create post</a></p>
			</div>
		
		</div>
		<!-- end Right 'create post' column  -->

	</div>
</div>

{% endblock content %}